package com.anticheat.client.util;

import java.util.HashSet;
import java.util.Set;

/**
 * Critical native module hashes (memory guard)
 * Auto-generated by generate_hashes.py
 * Contains SHA-256 truncated 64-bit hashes, no plaintext strings to avoid easy string search.
 * Collision probability: n / 2^64 ~ negligible.
 * False positives excluded: Sodium, OptiFine, Lunar, Badlion, etc.
 */
public final class CriticalModuleHashes {
    private static final Set<Long> HASHES = new HashSet<>();
    static {
        HASHES.add(-2639754072667000063L); // 0xdb5db5a82c4af301 : 'cheatengine'
        HASHES.add(-1293261641615316186L); // 0xee0d696391e16b26 : 'cheatengine-x86_64'
        HASHES.add(115210337390118848L); // 0x01994f31029747c0 : 'speedhack'
        HASHES.add(8006951283415891960L); // 0x6f1e67c505dcbff8 : 'artmoney'
        HASHES.add(9008607967772780104L); // 0x7d0501378fd9a648 : 'processhacker'
        HASHES.add(5211947436316065246L); // 0x48548e9449a07dde : 'x64dbg'
        HASHES.add(418531770904511020L); // 0x05ceec6d9bfa822c : 'ollydbg'
        HASHES.add(-5934806350293625737L); // 0xada3551180041477 : 'scylla'
        HASHES.add(-6228449012727993219L); // 0xa9901a9f66b72c7d : 'scylla_hide'
        HASHES.add(7887620115685046950L); // 0x6d7674b46ea1faa6 : 'titanengine'
        HASHES.add(6922085027739302020L); // 0x60102fa86f737884 : 'gameguard'
        HASHES.add(2741908539979269069L); // 0x260d374a341303cd : 'memoryscanner'
    }

    private CriticalModuleHashes() {}
    public static Set<Long> getHashes() { return HASHES; }
    public static boolean containsHash(long h) { return HASHES.contains(h); }
    public static int size() { return HASHES.size(); }
}
