package com.anticheat.client.util;

import java.util.HashSet;
import java.util.Set;

/**
 * Critical (ban) package hashes - curated excluding false positives like Sodium, OptiFine, Lunar, Badlion, etc.
 * Auto-generated by generate_hashes.py
 * Contains SHA-256 truncated 64-bit hashes, no plaintext strings to avoid easy string search.
 * Collision probability: n / 2^64 ~ negligible.
 * False positives excluded: Sodium, OptiFine, Lunar, Badlion, etc.
 */
public final class CriticalPackageHashes {
    private static final Set<Long> HASHES = new HashSet<>();
    static {
        HASHES.add(4768409575576765344L); // 0x422ccb3eafd303a0 : 'meteordevelopment.meteorclient'
        HASHES.add(-683162437999454315L); // 0xf684eb61d7271795 : 'meteordevelopment.meteorclient.mixin'
        HASHES.add(6363075778416460165L); // 0x584e2fb51b67c185 : 'meteordevelopment.meteorclient.systems.modules'
        HASHES.add(8971699064974166051L); // 0x7c81e0c3f77d4823 : 'net.wurstclient'
        HASHES.add(-7244588522359483814L); // 0x9b760d1f54e4125a : 'net.wurstclient.mixin'
        HASHES.add(-5474372698194223080L); // 0xb4071f0914096018 : 'net.wurstclient.forge'
        HASHES.add(8299770600595689944L); // 0x732eb5631dbc91d8 : 'net.wurstclient.altmanager'
        HASHES.add(5988377476901508142L); // 0x531afd9663aa142e : 'baritone'
        HASHES.add(4961577342214666282L); // 0x44db104e2054f82a : 'baritone.api'
        HASHES.add(2044191687566447351L); // 0x1c5e6d825e3452f7 : 'baritone.api.process'
        HASHES.add(-8071429248997378213L); // 0x8ffc85dcbfd0375b : 'baritone.mixin'
        HASHES.add(7406636337112256621L); // 0x66c9a881ae13906d : 'com.viaversion.aristois'
        HASHES.add(3842325382632351999L); // 0x3552ae93f744a8ff : 'net.aristois'
        HASHES.add(1903993337354559705L); // 0x1a6c57da3fbaa0d9 : 'me.deftware.aristois'
        HASHES.add(3449871046179724628L); // 0x2fe0677034729d54 : 'dev.tigr.ares'
        HASHES.add(-339337149817357712L); // 0xfb4a6ea8fe0afa70 : 'dev.tigr.ares.forge'
        HASHES.add(1876280985117535923L); // 0x1a09e39d70c02eb3 : 'me.kaimmy'
        HASHES.add(8647865217722444727L); // 0x78036398dfcd6bb7 : 'net.minecraft.client.gui.hud.impact'
        HASHES.add(3358368031987920868L); // 0x2e9b51ee83aaefe4 : 'com.impactclient'
        HASHES.add(-8057136470397100694L); // 0x902f4d119722dd6a : 'clientapi'
        HASHES.add(73559284213332755L); // 0x010555c77d77bb13 : 'com.mentalfrostburn.rusherhack'
        HASHES.add(579549504325655270L); // 0x080af9341f159ae6 : 'org.rusherhack.client'
        HASHES.add(3716042026446175813L); // 0x33920888dcbf3e45 : 'org.rusherhack.client.api.feature.module'
        HASHES.add(-3094848587584704209L); // 0xd50ce39b5764f12f : 'com.matt.forgehax'
        HASHES.add(507957926539945692L); // 0x070ca10afc41e6dc : 'me.rigamortis.seppuku'
        HASHES.add(-835985118129190475L); // 0xf465fbf6dc6589b5 : 'me.rigamortis.seppuku.impl.module'
        HASHES.add(-3280335372993090688L); // 0xd279e85bb4992b80 : 'com.krazzzzymonkey.cataclysm'
        HASHES.add(-243148029064105142L); // 0xfca02a27e3cc334a : 'dev.boze.havoc'
        HASHES.add(-5439120212625201403L); // 0xb4845cfbfbd3e705 : 'com.wildermods.wilderforge'
        HASHES.add(8215366927219949503L); // 0x7202d8b1846fffbf : 'me.zeroeightsix.elytra'
        HASHES.add(-2547181259692972657L); // 0xdca69823cd77e58f : 'dev.realms.future'
        HASHES.add(-4977114249262475737L); // 0xbaedbcf5ce2cd627 : 'me.futureclient'
        HASHES.add(-7579069222410588190L); // 0x96d1bcb2a61eefe2 : 'me.future.client'
        HASHES.add(-8605731948336472950L); // 0x88924c635b2c9c8a : 'net.novaclient'
        HASHES.add(1247812031411880478L); // 0x11511e6e6ec3821e : 'net.novac'
        HASHES.add(-9144793499821040250L); // 0x81172ac35add9d86 : 'wtf.expensive'
        HASHES.add(1521938496648529737L); // 0x151f02ffc6ba4749 : 'wtf.expensive.client'
        HASHES.add(7879239136991686491L); // 0x6d58ae3fc4beaf5b : 'expensiverp'
        HASHES.add(5670832048950587572L); // 0x4eb2d7b40299b0b4 : 'ru.krosik'
        HASHES.add(6827828984777307934L); // 0x5ec1524948c4771e : 'ru.dannzed'
        HASHES.add(7031732016712444719L); // 0x6195bb0373e2eb2f : 'net.zeus'
        HASHES.add(3945030334566454246L); // 0x36bf903007f953e6 : 'ru.nuxclient'
        HASHES.add(-822640985542760330L); // 0xf4956461d70be876 : 'ru.nursultan'
        HASHES.add(7466042795035859544L); // 0x679cb65d83fa1a58 : 'ru.celestial'
        HASHES.add(-8197582688876969235L); // 0x8e3c55fa2498c2ed : 'ru.nurik'
        HASHES.add(-5247503223435591262L); // 0xb72d1f9ee96781a2 : 'pw.prok.virtualhax'
        HASHES.add(4060762859372247550L); // 0x385aba4e45fb79fe : 'dev.rise.client'
        HASHES.add(8063158254623562633L); // 0x6fe617b64e989b89 : 'com.riseclient'
        HASHES.add(2175822567897271455L); // 0x1e321318f5cb8c9f : 'net.moonclient'
        HASHES.add(1318867926450495757L); // 0x124d8f6435bce10d : 'moonclient'
        HASHES.add(-83057506099236497L); // 0xfed8eba36506716f : 'me.liquidbounce'
        HASHES.add(7978887471381656495L); // 0x6ebab3e19a84b3af : 'net.ccbluex.liquidbounce'
        HASHES.add(4386759604896710997L); // 0x3ce0e69e5ce6c155 : 'net.ccbluex.liquidbounce.injection'
        HASHES.add(-3104498937290687760L); // 0xd4ea9aaa3535faf0 : 'net.ccbluex.liquidbounce.features.module'
        HASHES.add(708989949289052565L); // 0x09d6d69a3cb23995 : 'net.ccbluex.liquidbounce.event'
        HASHES.add(-2369527185630995925L); // 0xdf1dbf9436d55a2b : 'net.ccbluex.liquidbounce.utils'
        HASHES.add(-8401810276887818615L); // 0x8b66c6115fe00e89 : 'net.ccbluex.liquidbounce.ui.client.hud'
        HASHES.add(-1079393891768195562L); // 0xf10538f96c6e2616 : 'net.ccbluex.liquidbounce.injection.mixins'
        HASHES.add(-2174685370028606297L); // 0xe1d1f72d8d34bca7 : 'me.zero.alpine'
        HASHES.add(-1128981989885679182L); // 0xf0550cdc9f0ce9b2 : 'me.zero.alpine.listener'
        HASHES.add(3945533339185344802L); // 0x36c159aaeb9a7122 : 'com.lukflug.panelstudio'
        HASHES.add(3212295971863079253L); // 0x2c945e2abc512955 : 'net.freecam'
        HASHES.add(-457204950892729236L); // 0xf9a7ae85007d2c6c : 'dev.hashalite.freecam'
        HASHES.add(-8694648564911091358L); // 0x87566732499d5162 : 'net.zergatul.freecam'
        HASHES.add(1240079918198501976L); // 0x1135a61d89513258 : 'net.zergatul.cheatutils'
        HASHES.add(-7136740504230355444L); // 0x9cf53452cf351e0c : 'dev.xracha.freecam'
        HASHES.add(2654573946434793838L); // 0x24d6f0f09340b16e : 'mangoplex.spectatorfreecam'
        HASHES.add(-6620556715583714130L); // 0xa41f0ebe904e4cae : 'com.lambda.client'
        HASHES.add(2445388481713574599L); // 0x21efc3de2e5e92c7 : 'com.konasclient'
        HASHES.add(-3462960326527235384L); // 0xcff117ee3a12cac8 : 'com.inertia.client'
        HASHES.add(7101183225816245273L); // 0x628c78852bbd6419 : 'net.sigma'
    }

    private CriticalPackageHashes() {}
    public static Set<Long> getHashes() { return HASHES; }
    public static boolean containsHash(long h) { return HASHES.contains(h); }
    public static int size() { return HASHES.size(); }
}
