package com.anticheat.client.util;

import java.util.HashSet;
import java.util.Set;

/**
 * Critical file substring hashes (mods folder monitoring)
 * Auto-generated by generate_hashes.py
 * Contains SHA-256 truncated 64-bit hashes, no plaintext strings to avoid easy string search.
 * Collision probability: n / 2^64 ~ negligible.
 * False positives excluded: Sodium, OptiFine, Lunar, Badlion, etc.
 */
public final class CriticalFileHashes {
    private static final Set<Long> HASHES = new HashSet<>();
    static {
        HASHES.add(-2550294405568526655L); // 0xdc9b88c00b6c06c1 : 'meteor-client'
        HASHES.add(-7672143213007536858L); // 0x9587126582c2fd26 : 'meteorclient'
        HASHES.add(8268323362751680716L); // 0x72befc4a7ce090cc : 'wurst'
        HASHES.add(5988377476901508142L); // 0x531afd9663aa142e : 'baritone'
        HASHES.add(8072481072640309257L); // 0x700736c406ca3809 : 'aristois'
        HASHES.add(2293333336518926201L); // 0x1fd38e84dac59f79 : 'futureclient'
        HASHES.add(7396914494308414437L); // 0x66a71e8ac330f3e5 : 'future-client'
        HASHES.add(-5068049417145786644L); // 0xb9aaabe822e65eec : 'rusherhack'
        HASHES.add(5262046839282178769L); // 0x49068bb886e19ad1 : 'impactclient'
        HASHES.add(-8511418556342004737L); // 0x89e15deb1e9113ff : 'impact-client'
        HASHES.add(3753546670470934531L); // 0x341746cf45453003 : 'seppuku'
        HASHES.add(6535015212433927300L); // 0x5ab109b632e5ec84 : 'forgehax'
        HASHES.add(-907532933680150289L); // 0xf367cb9aea06c8ef : 'cataclysm'
        HASHES.add(485130875835364337L); // 0x06bb87f613bdb3f1 : 'havoc-client'
        HASHES.add(-566645773385594218L); // 0xf822deabdbe00a96 : 'wilderforge'
        HASHES.add(6534698786457442829L); // 0x5aafe9ec88f8da0d : 'elytra-client'
        HASHES.add(7105839246872404388L); // 0x629d03258cdbe1a4 : 'novaclient'
        HASHES.add(-5732638480596524726L); // 0xb07193acba4f214a : 'nova-client'
        HASHES.add(-879145901027848003L); // 0xf3cca575ff7e90bd : 'expensive'
        HASHES.add(8966284736447100388L); // 0x7c6ea4765eefb5e4 : 'nuxhack'
        HASHES.add(5264977453573837868L); // 0x4910f51956b5942c : 'nursultan'
        HASHES.add(917331599443998029L); // 0x0cbb043abe19b54d : 'celestial'
        HASHES.add(6101827963512066352L); // 0x54ae0c3435ae9130 : 'nurik'
        HASHES.add(-2561159987406609525L); // 0xdc74ee8fa1af638b : 'virtualhax'
        HASHES.add(5900939610275068649L); // 0x51e4594f9f7a3ae9 : 'rise-client'
        HASHES.add(-4397588370551146616L); // 0xc2f8a0ad28e8f788 : 'riseclient'
        HASHES.add(-5735929096690782901L); // 0xb065e2e076eb2d4b : 'liquidbounce'
        HASHES.add(5353024801434376296L); // 0x4a49c3b2035a1868 : 'inertia'
        HASHES.add(-4408532723013805876L); // 0xc2d1bed8881398cc : 'sigma-client'
        HASHES.add(-5048989796686354512L); // 0xb9ee6287d5f027b0 : 'sigma5'
        HASHES.add(-8002961387640856292L); // 0x90efc504fa7fe11c : 'vape'
        HASHES.add(486814775916729996L); // 0x06c183759ded968c : 'novoline'
        HASHES.add(6649413607596808837L); // 0x5c4776722d74da85 : 'tenacity'
        HASHES.add(-8499737033447915832L); // 0x8a0ade339d1abec8 : 'tenacity-client'
        HASHES.add(2805310524115914551L); // 0x26ee770efa980f37 : 'astolfo'
        HASHES.add(1540588193550397488L); // 0x156144ccb5bb7030 : 'flux-client'
        HASHES.add(2902427490610675860L); // 0x28477e6ccc2d8094 : 'raven-b'
        HASHES.add(5516905669369574731L); // 0x4c8ffc79fa1cb54b : 'ravenclient'
        HASHES.add(-3499892087867506603L); // 0xcf6de2b076750055 : 'thunderhack'
        HASHES.add(6399329312951019446L); // 0x58cefc1ae330a7b6 : 'thunder-hack'
        HASHES.add(1980283235059540349L); // 0x1b7b611c3c62a17d : 'akrien'
        HASHES.add(-6452504253382853205L); // 0xa6741991816afdab : 'matix'
        HASHES.add(-7098419380172252013L); // 0x9d7d592eca159c93 : 'huzuni'
        HASHES.add(-5806778530343938363L); // 0xaf6a2db1397c16c5 : 'kami-blue'
        HASHES.add(6937040996542502069L); // 0x60455208473cd4b5 : 'lambda-client'
        HASHES.add(-4670254782159910197L); // 0xbf2fec050aca0acb : 'konas'
        HASHES.add(-727054160300170990L); // 0xf5e8fc17e2d6a112 : 'salhack'
        HASHES.add(-5450919901564746181L); // 0xb45a713ad020463b : 'phobos'
        HASHES.add(-7880609838978378998L); // 0x92a2731ace3ed30a : 'jigsaw-client'
        HASHES.add(-5168086339781409463L); // 0xb84744db0cc7c549 : 'wolfram'
        HASHES.add(9011001485472851416L); // 0x7d0d821bd42065d8 : 'ares-client'
        HASHES.add(-5084657198182716343L); // 0xb96fab37c9afac49 : 'fdpclient'
        HASHES.add(5872777623931057402L); // 0x51804c223745f4fa : 'fdp-client'
        HASHES.add(-1786180301276974015L); // 0xe736367ac595f441 : 'nova-line'
        HASHES.add(592145677064203812L); // 0x0837b95b20b1ee24 : 'killaura'
        HASHES.add(-1837573769923629252L); // 0xe67fa06463206f3c : 'kill-aura'
        HASHES.add(-738340067231797406L); // 0xf5c0e39ee935ef62 : 'autocrystal'
        HASHES.add(3235784751394776607L); // 0x2ce7d1166482e61f : 'auto-crystal'
        HASHES.add(-1245165162431684427L); // 0xeeb848e1c69160b5 : 'crystalpvp'
        HASHES.add(-4272425407248132655L); // 0xc4b54bba779f15d1 : 'xray-mod'
        HASHES.add(893062499504585146L); // 0x0c64cb9c953179ba : 'x-ray-fabric'
        HASHES.add(7521045924204688269L); // 0x68601f6b7b9eb38d : 'freecam-mod'
        HASHES.add(-8403091816430670616L); // 0x8b623883b2a86ce8 : 'entityradar'
        HASHES.add(-337839191643294676L); // 0xfb4fc10b8ee5742c : 'xraybypass'
        HASHES.add(-991880502479510658L); // 0xf23c21f02e12a37e : 'autoclicker-mod'
        HASHES.add(6531106781571486561L); // 0x5aa32703b9b69361 : 'reach-mod'
        HASHES.add(765355337568484946L); // 0x0a9f169fdeb7fe52 : 'flyhack'
        HASHES.add(4552874952735674303L); // 0x3f2f0fa5b8954fbf : 'bhop'
        HASHES.add(115210337390118848L); // 0x01994f31029747c0 : 'speedhack'
        HASHES.add(-8269941784962983308L); // 0x8d3b43c33a1f1a74 : 'nursultan-client'
        HASHES.add(-8645085432348620797L); // 0x88067c9a57f4c803 : 'celestial-client'
        HASHES.add(9083786002759428660L); // 0x7e10173dd6242a34 : 'expensive-client'
        HASHES.add(-6775531956517888716L); // 0xa1f8799577719d34 : 'akrien-client'
    }

    private CriticalFileHashes() {}
    public static Set<Long> getHashes() { return HASHES; }
    public static boolean containsHash(long h) { return HASHES.contains(h); }
    public static int size() { return HASHES.size(); }
}
