package com.anticheat.client.util;

import java.util.HashSet;
import java.util.Set;

/**
 * Suspicious file substring hashes
 * Auto-generated by generate_hashes.py
 * Contains SHA-256 truncated 64-bit hashes, no plaintext strings to avoid easy string search.
 * Collision probability: n / 2^64 ~ negligible.
 * False positives excluded: Sodium, OptiFine, Lunar, Badlion, etc.
 */
public final class SuspiciousFileHashes {
    private static final Set<Long> HASHES = new HashSet<>();
    static {
        HASHES.add(-1170865371701353596L); // 0xefc04025dfef6384 : 'tweakeroo'
        HASHES.add(-1555880778466719864L); // 0xea6866ace6a20788 : 'litematica'
        HASHES.add(6755705950938945637L); // 0x5dc116c4e4b55865 : 'xaerominimap'
        HASHES.add(8468215476406385206L); // 0x7585251bf8aafa36 : 'xaeroworldmap'
        HASHES.add(4043848202880098794L); // 0x381ea283ea4521ea : 'voxelmap'
        HASHES.add(1461815384935635570L); // 0x14496958fa4a1a72 : 'free-cam'
        HASHES.add(-7275974611513507136L); // 0x9b068ba3fdfa02c0 : 'freecam'
        HASHES.add(-1443028823529168054L); // 0xebf954ee34e4e34a : 'cheatutils'
        HASHES.add(-3790595013232856801L); // 0xcb6519eb3ce3711f : 'zergatul'
    }

    private SuspiciousFileHashes() {}
    public static Set<Long> getHashes() { return HASHES; }
    public static boolean containsHash(long h) { return HASHES.contains(h); }
    public static int size() { return HASHES.size(); }
}
