package com.anticheat.client.util;

import java.util.HashSet;
import java.util.Set;

/**
 * Suspicious package hashes (warning level)
 * Auto-generated by generate_hashes.py
 * Contains SHA-256 truncated 64-bit hashes, no plaintext strings to avoid easy string search.
 * Collision probability: n / 2^64 ~ negligible.
 * False positives excluded: Sodium, OptiFine, Lunar, Badlion, etc.
 */
public final class SuspiciousPackageHashes {
    private static final Set<Long> HASHES = new HashSet<>();
    static {
        HASHES.add(669341301942244445L); // 0x0949fa5e27c3d45d : 'fi.dy.masa.tweakeroo'
        HASHES.add(-1698584756144275155L); // 0xe86d6a29ed20812d : 'fi.dy.masa.litematica'
        HASHES.add(7989107308135122350L); // 0x6edf02c4c5df05ae : 'xaero.map'
        HASHES.add(-3420256667495311803L); // 0xd088ceaea547d645 : 'xaero.common.minimap'
        HASHES.add(-4739656481222168918L); // 0xbe395b8ac75feeaa : 'journeymap'
        HASHES.add(-6599027978231898156L); // 0xa46b8b04569f9fd4 : 'com.mamiyaotaru.voxelmap'
    }

    private SuspiciousPackageHashes() {}
    public static Set<Long> getHashes() { return HASHES; }
    public static boolean containsHash(long h) { return HASHES.contains(h); }
    public static int size() { return HASHES.size(); }
}
